### ISSUE TITLE
openfile with default app

### ISSUE THREAD

**Issue by guidoDimasi** [Marowota/MaiFileManager#2]
Hi, i'm building something similar.
i'm having hard time to implement an "open with default app" command.
with the launcher api https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/launcher?view=net-maui-8.0 or with a custom Intent i can open a file in read-only mode.
have you come to a solution to open a file with its default app in a way that is possibile to edit it?

**Comment by Marowota** [comment]
Hi, sorry for late reply
Have you tried to open the file and edit it with supported application to edit it (like WPS for .docx)? I have looked up to the open source of MAUI and see that the ReadOnlyMode object used in that Laucher api doesn't use the OpenReadAsync method supported by that object, it only use the property of that object (The OpenAsync method of shared code (https://github.com/dotnet/maui/blob/main/src/Essentials/src/Launcher/Launcher.shared.cs#L155) called platformOpenAsync method (https://github.com/dotnet/maui/blob/main/src/Essentials/src/Launcher/Launcher.android.cs#L31) which called GetShareableFileUri and use the ReadOnlyMode object here
https://github.com/dotnet/maui/blob/main/src/Essentials/src/FileSystem/FileSystemUtils.android.cs#L351 ()) so I think the read-only mode doesnt related to that class (which suspiciously called ReadOnlyFile)

**Comment by guidoDimasi** [comment]
so far i've managed to open a file writing a custom android service.
the service create an intent that open the desired file (stored in the documents folder of the device) with excel or word app.
with this method the the default app seems to be in "write" mode and can save the file after editing it.
there is one major drawback : the intent works only below android sdk v23.

i'll attach the code:

`
 Java.IO.File myDir = new(full_path_dir);
 myDir.Mkdir();
 Java.IO.File file = new(myDir, filename);
 file.SetReadable(true);
 file.SetExecutable(true);
 file.SetWritable(true, false);

 if (!file.Exists()) return;
 if (!file.CanRead()) return;
 if (!file.CanWrite()) return;

var intent = new Intent(Intent.ActionView);
intent.AddFlags(ActivityFlags.NewTask);
intent.AddFlags(ActivityFlags.NoHistory);
intent.AddFlags(ActivityFlags.GrantReadUriPermission);
intent.AddFlags(ActivityFlags.GrantWriteUriPermission);

string mimeType = Java.Nio.FileNio.Files.ProbeContentType(file.ToPath());
intent.SetDataAndType(Android.Net.Uri.FromFile(file), mimeType);
Android.App.Application.Context.StartActivity(intent);

`

**Comment by Marowota** [comment]
Have you tried to grant permission before start activity? Because since Android 6.0, runtime permission has been introduced, which means that certain permissions, such as reading from or writing to external storage, need to be requested at runtime, not just declared in the manifest. So to open it, you need to check if the required permissions have been granted before trying to open the file.

**Comment by guidoDimasi** [comment]
every permission is granted:
- i can use the filemanager
- i can see the file in every folder (/documents, /media, /donwloads)

**Comment by guidoDimasi** [comment]
for what i know seems something more related to the android ecosystem that maui.

**Comment by Marowota** [comment]
or maybe something related to the way to get uri with FileProvider in new version, like this:
```
 if (Build.VERSION.SdkInt >= BuildVersionCodes.N) {
        Uri fileUri = FileProvider.GetUriForFile(this, this.ApplicationContext.PackageName + ".provider", file);
        intent.SetDataAndType(fileUri, mimeType);
    } else {
        intent.SetDataAndType(Android.Net.Uri.FromFile(file), mimeType);
}
```
